server:
  port: 8080
  servlet:
    context-path: /myboot
spring:
  thymeleaf:
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
  datasource:
    url:jdbc:mysql://127.0.0.1:3306/boot
    username:admin
    password:123456
    driver-class-name: com.mysql.jdbc.Driver